[package]
name = "realworld-rust-fullstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
actix-web = "4"
actix-session = { version = "0.7", features = ["cookie-session"] }
sqlx = { version = "0.6", features = [ "runtime-actix-native-tls" , "postgres", "chrono", "offline" ] }
chrono = { version = "0.4", features = [ "serde" ]}
tokio = "1"
tera = "1"
lazy_static = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
regex = "1"

shuttle-runtime = "0.16"
shuttle-actix-web = "0.16"
shuttle-shared-db = { version = "0.16", features = ["postgres"] }
shuttle-secrets = "0.16"
shuttle-static-folder = "0.16"

once_cell = "1"
