[package]
name = "realworld-rust-fullstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-session = { version = "0.7", features = ["cookie-session"] }
sqlx = { version = "0.6", features = [ "runtime-actix-native-tls" , "postgres", "chrono" ] }
chrono = { version = "0.4", features = [ "serde" ]}
tokio = "1"
env_logger = "0.10"
dotenvy = "0.15"
tera = "1"
lazy_static = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"

shuttle-service = { version = "0.8", features = ["web-actix-web"] }
shuttle-shared-db = { version = "0.8", features = ["postgres"] }
shuttle-secrets = "0.8"
