name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: realworld
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JFB3VXMXEZGBA9A330F7STJF
          working-directory: '.'
          cargo-shuttle-version: '0.49.0'
          extra-args: --no-test --allow-dirty
          secrets: |
            COOKIE_SECRET = '${{ secrets.COOKIE_SECRET }}'
